FROM node:22-alpine
RUN corepack enable
WORKDIR /app/frontend
COPY frontend .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @telepace/app build
ENV NODE_ENV=production
EXPOSE 3300
CMD ["pnpm", "--filter", "@telepace/app", "start"]
